In [64]:
import numpy as np
import pickle as pickle
import os

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score

path_data = r"/Users/sidou/Desktop/gmda/data"

In [40]:
# Import data
f = open(os.path.join(path_data, "data_acc_rot.dat"),"rb")
data = pickle.load(f,encoding="latin1")
f.close()

data_A = np.array(data[0])
data_B = np.array(data[1])
data_C = np.array(data[2])
label = data[3]

# 6) Do the same experiment as previously, but using the raw data ( 3 × 200 array of acceleration coordi- nates). Compare the obtained classification results to the previous one.

In [56]:
print(type(data_A))
print("# individuals: {}".format(len(data_A)))
print("# points along a direction: {}".format(len(data_A[0])))
print("# of directions: {}".format(len(data_A[0][0])))

print("Example of 1 individual:\n {}".format(data_A[0]))

<class 'numpy.ndarray'>
# individuals: 100
# points along a direction: 200
# of directions: 3
Example of 1 individual:
 [[ -1.33597108e-02   2.03704449e+00   4.53778011e-01]
 [ -1.22212725e-01   9.84604407e-01   7.54364139e-01]
 [  5.96210366e-01   1.27607556e+00   2.52214017e-02]
 [  4.61930138e-01   5.50613865e-01   8.52447037e-01]
 [  3.64615934e-01   4.95419152e-01  -3.75068611e-01]
 [  1.48705618e-01   1.31868865e+00  -5.57132487e-01]
 [  1.21970218e-01   9.08640000e-01  -9.85069953e-02]
 [  4.24552220e-01   6.69800455e-01   2.49743836e-02]
 [  3.03482417e-01   8.40529068e-01  -1.61090176e-01]
 [  2.21348488e-01   8.82028647e-01  -8.70710108e-02]
 [  1.91261827e-01   9.89772405e-01   3.48958545e-02]
 [  1.10306464e-01   9.69843497e-01  -1.18117315e-01]
 [  1.99424980e-01   1.06387912e+00   4.68350993e-02]
 [  1.58980464e-01   1.13856814e+00  -1.10556181e-01]
 [  5.85603549e-02   1.19663888e+00  -3.98749347e-02]
 [  3.69446619e-01   1.47633793e+00  -9.48818849e-02]
 [  4.72592623e-

In [47]:
def flatten(data):
    list_result = [individual.flatten() for individual in data]
    return np.array(list_result)

In [48]:
# Flatten the list to get 100 rows of 600 points
flat_data_A = flatten(data_A)
print(type(data_A))
print("# individuals: {}".format(len(flat_data_A)))
print("# points per individual: {}".format(len(flat_data_A[0])))

<class 'numpy.ndarray'>
# individuals: 100
# points per individual: 600


In [68]:
# Concatenating data from 3 sources
flat_data_B = flatten(data_B)
flat_data_C = flatten(data_C)

X = np.concatenate((flat_data_A, flat_data_B, flat_data_C))
X.shape

(300, 600)

In [91]:
# Classifying using raw data
clf = RandomForestClassifier(random_state=42)
cv = StratifiedKFold(n_splits=5)
print("Mean of cross-validation accuracy: {:.2f}".format(cross_val_score(clf, X, label, cv=cv, scoring='accuracy').mean()))

Mean of cross-validation accuracy: 0.93


In [111]:
# Test on 1 specific example from A
split = next(cv.split(X,label))
(X_train, y_train) = (X[split[0]], label[split[0]])
(X_test, y_test) = (X[split[1]], label[split[1]])

In [112]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [116]:
clf.predict(X_test)

array([b'A', b'B', b'A', b'A', b'A', b'A', b'A', b'A', b'A', b'A', b'A',
       b'A', b'A', b'A', b'A', b'A', b'A', b'A', b'A', b'A', b'B', b'B',
       b'B', b'A', b'B', b'B', b'B', b'B', b'B', b'B', b'B', b'B', b'B',
       b'B', b'B', b'B', b'B', b'B', b'B', b'B', b'C', b'C', b'C', b'C',
       b'C', b'C', b'C', b'C', b'C', b'B', b'C', b'C', b'C', b'C', b'C',
       b'C', b'C', b'C', b'C', b'C'],
      dtype='|S1')